using Xunit;
using EllipticCurve;

namespace StarkbankEcdsaTests {

    public class TestOpenSsl {

        [Fact]
        public void testAssign() {
            // Generated by: openssl ecparam -name secp256k1 -genkey -out privateKey.pem
            string privateKeyPem = EllipticCurve.Utils.File.read("privateKey.pem");
            PrivateKey privateKey = PrivateKey.fromPem(privateKeyPem);

            string message = EllipticCurve.Utils.File.read("message.txt");

            Signature signature = Ecdsa.sign(message, privateKey);

            PublicKey publicKey = privateKey.publicKey();

            Assert.True(Ecdsa.verify(message, signature, publicKey));
        }

        [Fact]
        public void testVerifySignature() {
            // openssl ec -in privateKey.pem -pubout -out publicKey.pem
            string publicKeyPem = EllipticCurve.Utils.File.read("publicKey.pem");

            // openssl dgst -sha256 -sign privateKey.pem -out signature.binary message.txt
            string signatureDer = EllipticCurve.Utils.File.read("tests/signatureDer.txt");

            string message = EllipticCurve.Utils.File.read("message.txt");

            PublicKey publicKey = PublicKey.fromPem(publicKeyPem);
            Signature signature = Signature.fromDer(signatureDer);

            Assert.True(Ecdsa.verify(message, signature, publicKey));
        }

    }

}
